name = "Azalea"
tagline = "Like an umbrella, it can protect you from a cloud."
author = "Ethan Martin"
author_link = "https://website-21n.pages.dev"
github_link = "https://github.com/yuckdevchan/cannit"
copyright_year_range = "2026"
contact_email = "fd0acijfg@mozmail.com"

version = "1.3a"
subsonic_version = "1.16.1"
garbage_files = ["desktop.ini", ".DS_Store"]

[apps.Music.Android.Tempus.links]
"IzzyOnDroid" = "https://apt.izzysoft.de/fdroid/index/apk/com.eddyizm.degoogled.tempus"
"OpenAPK" = "https://www.openapk.net/tempus/com.eddyizm.degoogled.tempus/"
"Obtainium" = "https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.eddyizm.tempus%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Feddyizm%2Ftempus%22%2C%22author%22%3A%22eddyizm%22%2C%22name%22%3A%22Tempus%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22sortMethodChoice%5C%22%3A%5C%22date%5C%22%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22releaseTitleAsVersion%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22tempus%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22appAuthor%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22refreshBeforeDownload%5C%22%3Afalse%2C%5C%22includeZips%5C%22%3Afalse%2C%5C%22zippedApkFilterRegEx%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D"
"GitHub" = "https://github.com/eddyizm/tempus/releases"

[apps.Music.Android.Ultrasonic.links]
"Google Play" = "https://play.google.com/store/apps/details?id=org.moire.ultrasonic"
"F-Droid" = "https://f-droid.org/en/packages/org.moire.ultrasonic/#latest"
"GitLab" = "https://gitlab.com/ultrasonic/ultrasonic/-/releases"

[apps.Music.Desktop.Strawberry.links]
"Website" = "https://www.strawberrymusicplayer.org/#download"

[apps.Music.Desktop.SPlayer.links]
"GitHub" = "https://github.com/imsyy/SPlayer"
"Website" = "http://splayer.imsyy.top/"

[apps.Music.Web."Azalea Web".links]
"GitHub" = "https://github.com/yuckdevchan/azalea-web"
